---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: hello
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./namespaces/hello-world
  prune: true
  sourceRef:
    kind: GitRepository
    name: hello-world
    namespace: flux-system
  validation: client